### ISSUE TITLE
Add icon for security code.

### ISSUE THREAD

**Issue by muffinresearch** [muffinresearch/payment-icons#3]
It's a pretty common case people would like a visual pointer for the ccv/cid security code.

**Comment by zemirco** [comment]
That would be awesome :)

**Comment by muffinresearch** [comment]
This should be fixed in https://github.com/muffinresearch/payment-icons/commit/aa97ae9d69f4a6c0edd83bf6bf026b88b85a3aa0 and released in 0.0.8.
