### ISSUE TITLE
Visa using old logo

### ISSUE THREAD

**Issue by yatrix7** [muffinresearch/payment-icons#43]
The Visa svg is still using the orange flick, which has since been removed. 

Via wikipedia, 
> The orange flick was removed in favor of the logo being a solid blue gradient in 2014. In 2015, the gold and blue stripes were restored as card branding on Visa Debit and Visa Electron, although not as the company's logotype.

For reference, https://usa.visa.com/

**Comment by muffinresearch** [comment]
Fixed and released in 1.2.0

**Comment by muffinresearch** [comment]
Deployment is having issues at the moment. I'll update this again once the deployment has completed successfully.

**Comment by muffinresearch** [comment]
Finally deployed in 1.2.1
