### ISSUE TITLE
Create a generic credit card

### ISSUE THREAD

**Issue by bseib** [muffinresearch/payment-icons#5]
What credit card image shall we show when the card type is "unknown"?  No matter how thorough we programmers may be in covering "all cases", there's always the final else-clause where we must punt. For this case it would be nice to have a generic card SVG that does not belong to any brand.

Presently I use Font Awesome's credit card icon (below), which can be scaled up, but doesn't look as nice at large scale. Would be nice to have a generic SVG card image from this family of images you've created.

![image](https://cloud.githubusercontent.com/assets/1313561/13198147/34564524-d7cf-11e5-939f-75ee0e1befb8.png)

**Comment by muffinresearch** [comment]
This should be fixed in https://github.com/muffinresearch/payment-icons/commit/aa97ae9d69f4a6c0edd83bf6bf026b88b85a3aa0 and released in 0.0.8.
