### ISSUE TITLE
New MasterCard Logo

### ISSUE THREAD

**Issue by theopak** [muffinresearch/payment-icons#6]
<img width="800" alt="screen shot 2016-08-29 at 6 14 21 pm" src="https://cloud.githubusercontent.com/assets/693878/18069337/7d1aec16-6e14-11e6-9dc5-f66fb9a1ec28.png">

Thanks for really excellent work! This is a really awesome npm module.

MasterCard introduced a new logo last month which will replace the mark seen in payment-icons. See screenshot above from this article about the change: http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mastercard_by_pentagram.php 

**Are there any plans to update the icons in this package so they're in line with this change?** According to MasterCard, new brand marks will be available here on September 30: http://www.mastercardbrandcenter.com/us/index.shtml

Thanks again!

**Comment by muffinresearch** [comment]
It would be great to get this updated. We can look at this as soon as the definitive source is released.

**Comment by LKay** [comment]
The new MasterCard logo is officially out. Can we expect it to be updated any soon? Also I think it would be nice to preserve the old logo under `mastercard-old` name maybe?

Seems like Maestro and Cirrus have not got the logo updates.

**Comment by muffinresearch** [comment]
> The new MasterCard logo is officially out. Can we expect it to be updated any soon? Also I think it would be nice to preserve the old logo under mastercard-old name maybe?

Not sure when I'll get a chance to add this, but it should be relatively straight-forward. Definitely happy to take a patch if anyone would like it sooner. If anyone wants to take this on just drop a comment here so we know it's in progress.

+1 to retaining the old logos with an `-old` suffix.

> Seems like Maestro and Cirrus have not got the logo updates.

Looks they are available here: https://brand.mastercard.com/brandcenter/other-marks.html

**Comment by LKay** [comment]
Yeah, that should be pretty straight forward especially the svg files are already there. This might be also a good time to update maestro and maybe add cirrus?

**Comment by pableco** [comment]
Hello, maybe is time to update the mastercard's logos. It seems they have updated all brands.

**Comment by muffinresearch** [comment]
The new icons landed in master thanks to @longmd - I'll cut a new release in due course.
