### ISSUE TITLE
UnionPay icon

### ISSUE THREAD

**Issue by LKay** [muffinresearch/payment-icons#9]
Any plans on adding UnionPay card icons soon?

* [Color](http://media.idownloadblog.com/wp-content/uploads/2014/11/unionpay-logo.jpg)
* [Mono](http://image.flaticon.com/icons/png/512/39/39141.png)

**Comment by muffinresearch** [comment]
@LKay no plans, but I would happily look at a Pull Request to add it to all of the icon sets.
